# Generated by Django 5.1.4 on 2024-12-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAPI', '0002_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student'), (4, 'Parent'), (5, 'Manager')], default=2),
        ),
    ]
